backend:
  name: github
  repo: polygecko/haliflocks
  branch: main

media_folder: public/images/uploads
public_folder: /images/uploads

collections:
  - name: events
    label: Events
    folder: content/events
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Location, name: location, widget: string }
      - { label: Description, name: body, widget: markdown }
      - label: Tour Type
        name: type
        widget: select
        options:
          - { label: Scheduled Guided Tour, value: scheduled }
          - { label: Personalized Guided Tour, value: personalized }
        default: scheduled
      - { label: Featured Image, name: image, widget: image, required: false }